version: "3.7"
services:
  # MySQL
  why-mysql:
    image: mysql:latest
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=00000000
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"